services:
  tempo_worklog_automation:
    image: tempo_worklog_automation:0.1.0
    build:
      context: .
    environment:
      TEMPO_WORKLOG_AUTOMATION_ENVIRONMENT: ${TEMPO_WORKLOG_AUTOMATION_ENVIRONMENT}
      TEMPO_WORKLOG_AUTOMATION_LOG_LEVEL: ${TEMPO_WORKLOG_AUTOMATION_LOG_LEVEL}
      TEMPO_WORKLOG_AUTOMATION_RUN_INTEGRATION_TESTS: ${TEMPO_WORKLOG_AUTOMATION_RUN_INTEGRATION_TESTS}
      TEMPO_WORKLOG_AUTOMATION_JIRA_ACCOUNT_EMAIL: ${TEMPO_WORKLOG_AUTOMATION_JIRA_ACCOUNT_EMAIL}
      TEMPO_WORKLOG_AUTOMATION_JIRA_TOKEN: ${TEMPO_WORKLOG_AUTOMATION_JIRA_TOKEN}
      TEMPO_WORKLOG_AUTOMATION_JIRA_BASE_API_URL: ${TEMPO_WORKLOG_AUTOMATION_JIRA_BASE_API_URL}
      TEMPO_WORKLOG_AUTOMATION_TEMPO_OAUTH_TOKEN: ${TEMPO_WORKLOG_AUTOMATION_TEMPO_OAUTH_TOKEN}
      TEMPO_WORKLOG_AUTOMATION_AUTHOR_ACCOUNT_ID: ${TEMPO_WORKLOG_AUTOMATION_AUTHOR_ACCOUNT_ID}
      TEMPO_WORKLOG_AUTOMATION_TEMPO_BASE_API_URL: ${TEMPO_WORKLOG_AUTOMATION_TEMPO_BASE_API_URL}
    volumes:
      - ./data:/app/data
    command: --file-path /app/data/<CSV_FILE_NAME>.csv
